sudo: required
language: node_js
node_js:
  - 10
install:
  - npm install
script:
  - npm run test
  - npm run build

deploy:
  provider: script
  script: bash ./scripts/deploy.sh staging
  on:
    branch: staging

deploy:
  provider: script
  script: bash ./scripts/deploy.sh default
  on:
    branch: master
