sudo: required
language: node_js
node_js:
  - lts/*
install:
  - npm install

  - cd functions
  - npm install
  - npm run build
  - cd ..
script:
  - npm run test:ci
  - npm run build

before_deploy:
  - cd functions
  - npm install
  - cd ..

deploy:
  - provider: script
    skip_cleanup: true
    script: npm install -g firebase-tools && firebase use staging --token $FIREBASE_DEPLOY_KEY && firebase deploy -f --token $FIREBASE_DEPLOY_KEY
    on:
      branch: staging

  - provider: script
    skip_cleanup: true
    script: npm install -g firebase-tools && firebase use production --token $FIREBASE_DEPLOY_KEY && firebase deploy -f --token $FIREBASE_DEPLOY_KEY
    on:
      branch: master
