sudo: required

language: node_js
node_js:
  - node

before_install:
  - openssl aes-256-cbc -K $encrypted_357e5deb27f8_key -iv $encrypted_357e5deb27f8_iv -in keys/travis-deployer.json.enc -out ./keys/travis-deployer.json -d

script:
  # - npm test -- --coverage
  - npm run test

deploy:
  - provider: gae
    project: tekktekk
    keyfile: ./keys/travis-deployer-service-account.json
    verbosity: debug
    on: master

  - provider: gae
    project: tekktekk
    keyfile: ./keys/travis-deployer-service-account.json
    verbosity: debug
    on: master
