sudo: required

language: node_js
node_js:
  - node

before_install:
  - openssl aes-256-cbc -K $encrypted_357e5deb27f8_key -iv $encrypted_357e5deb27f8_iv -in ./keys/travis-deployer.json.enc -out ./keys/travis-deployer.json -d

install:
  - cd client && npm install && npm run build && cd ..
  - cd server && npm install && cd ..

script:
  - npm run test

deploy:
  - provider: gae
    project: tekktekk
    keyfile: ./keys/travis-deployer.json
    config: 'dispatch.yaml'
    verbosity: debug
    on: master

  - provider: gae
    project: tekktekk
    keyfile: ./keys/travis-deployer.json
    config: './client/app.yaml'
    verbosity: debug
    on: master

  - provider: gae
    project: tekktekk
    keyfile: ./keys/travis-deployer.json
    config: './server/app.yaml'
    verbosity: debug
    on: master
