sudo: required
language: node_js
node_js:
  - 10
install:
  - npm install
script:
  - npm run test
  - npm run build

deploy:
  - provider: script
    script: npm install -g firebase-tools && firebase use --token $FIREBASE_DEPLOY_KEY staging && firebase deploy --token $FIREBASE_DEPLOY_KEY
    on:
      branch: staging

  - provider: script
    script: npm install -g firebase-tools && firebase use default --token $FIREBASE_DEPLOY_KEY && firebase deploy --token $FIREBASE_DEPLOY_KEY
    on:
      branch: master
