sudo: required
language: node_js
node_js:
  - 10
install:
  - npm install
script:
  - npm run test

before_deploy:
  - npm run build
  - cd functions
  - npm install
  - cd ..

deploy:
  - provider: script
    skip_cleanup: true
    script: npm install -g firebase-tools && firebase use --token $FIREBASE_DEPLOY_KEY staging && firebase deploy --token $FIREBASE_DEPLOY_KEY
    on:
      branch: staging

  - provider: script
    skip_cleanup: true
    script: npm install -g firebase-tools && firebase use default --token $FIREBASE_DEPLOY_KEY && firebase deploy --token $FIREBASE_DEPLOY_KEY
    on:
      branch: master
