sudo: required

language: node_js
node_js:
  - 10

before_install:
  - openssl aes-256-cbc -K $encrypted_4b0974dc0a55_key -iv $encrypted_4b0974dc0a55_iv -in ./keys/travis-service-account.json.enc -out ./keys/travis-service-account.json -d

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "dispatch.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "app.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master
