# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy to Firebase
        env:
          APP_MODE: staging
        run: |
          npm install -g firebase-tools
          firebase use production --token ${{ secrets.FIREBASE_DEPLOY_KEY }}
          firebase deploy -f --token ${{ secrets.FIREBASE_DEPLOY_KEY }}
