# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: |
          cd functions
          npm install
          cd ..
      - name: Deploy to Firebase
        env:
          APP_MODE: production
        run: |
          npm install -g firebase-tools
          firebase use production --token ${{ secrets.FIREBASE_DEPLOY_KEY }}
          firebase deploy -f --token ${{ secrets.FIREBASE_DEPLOY_KEY }}
